# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/francois/Documents/travail/B5/IA/gomoku

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/francois/Documents/travail/B5/IA/gomoku

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/francois/Documents/travail/B5/IA/gomoku/CMakeFiles /home/francois/Documents/travail/B5/IA/gomoku/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/francois/Documents/travail/B5/IA/gomoku/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gomoku

# Build rule for target.
gomoku: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gomoku
.PHONY : gomoku

# fast build rule for target.
gomoku/fast:
	$(MAKE) -f CMakeFiles/gomoku.dir/build.make CMakeFiles/gomoku.dir/build
.PHONY : gomoku/fast

moc_GomokuWindow.o: moc_GomokuWindow.cpp.o

.PHONY : moc_GomokuWindow.o

# target to build an object file
moc_GomokuWindow.cpp.o:
	$(MAKE) -f CMakeFiles/gomoku.dir/build.make CMakeFiles/gomoku.dir/moc_GomokuWindow.cpp.o
.PHONY : moc_GomokuWindow.cpp.o

moc_GomokuWindow.i: moc_GomokuWindow.cpp.i

.PHONY : moc_GomokuWindow.i

# target to preprocess a source file
moc_GomokuWindow.cpp.i:
	$(MAKE) -f CMakeFiles/gomoku.dir/build.make CMakeFiles/gomoku.dir/moc_GomokuWindow.cpp.i
.PHONY : moc_GomokuWindow.cpp.i

moc_GomokuWindow.s: moc_GomokuWindow.cpp.s

.PHONY : moc_GomokuWindow.s

# target to generate assembly for a file
moc_GomokuWindow.cpp.s:
	$(MAKE) -f CMakeFiles/gomoku.dir/build.make CMakeFiles/gomoku.dir/moc_GomokuWindow.cpp.s
.PHONY : moc_GomokuWindow.cpp.s

src/ASFMLCanvas.o: src/ASFMLCanvas.cpp.o

.PHONY : src/ASFMLCanvas.o

# target to build an object file
src/ASFMLCanvas.cpp.o:
	$(MAKE) -f CMakeFiles/gomoku.dir/build.make CMakeFiles/gomoku.dir/src/ASFMLCanvas.cpp.o
.PHONY : src/ASFMLCanvas.cpp.o

src/ASFMLCanvas.i: src/ASFMLCanvas.cpp.i

.PHONY : src/ASFMLCanvas.i

# target to preprocess a source file
src/ASFMLCanvas.cpp.i:
	$(MAKE) -f CMakeFiles/gomoku.dir/build.make CMakeFiles/gomoku.dir/src/ASFMLCanvas.cpp.i
.PHONY : src/ASFMLCanvas.cpp.i

src/ASFMLCanvas.s: src/ASFMLCanvas.cpp.s

.PHONY : src/ASFMLCanvas.s

# target to generate assembly for a file
src/ASFMLCanvas.cpp.s:
	$(MAKE) -f CMakeFiles/gomoku.dir/build.make CMakeFiles/gomoku.dir/src/ASFMLCanvas.cpp.s
.PHONY : src/ASFMLCanvas.cpp.s

src/Game.o: src/Game.cpp.o

.PHONY : src/Game.o

# target to build an object file
src/Game.cpp.o:
	$(MAKE) -f CMakeFiles/gomoku.dir/build.make CMakeFiles/gomoku.dir/src/Game.cpp.o
.PHONY : src/Game.cpp.o

src/Game.i: src/Game.cpp.i

.PHONY : src/Game.i

# target to preprocess a source file
src/Game.cpp.i:
	$(MAKE) -f CMakeFiles/gomoku.dir/build.make CMakeFiles/gomoku.dir/src/Game.cpp.i
.PHONY : src/Game.cpp.i

src/Game.s: src/Game.cpp.s

.PHONY : src/Game.s

# target to generate assembly for a file
src/Game.cpp.s:
	$(MAKE) -f CMakeFiles/gomoku.dir/build.make CMakeFiles/gomoku.dir/src/Game.cpp.s
.PHONY : src/Game.cpp.s

src/GomokuWindow.o: src/GomokuWindow.cpp.o

.PHONY : src/GomokuWindow.o

# target to build an object file
src/GomokuWindow.cpp.o:
	$(MAKE) -f CMakeFiles/gomoku.dir/build.make CMakeFiles/gomoku.dir/src/GomokuWindow.cpp.o
.PHONY : src/GomokuWindow.cpp.o

src/GomokuWindow.i: src/GomokuWindow.cpp.i

.PHONY : src/GomokuWindow.i

# target to preprocess a source file
src/GomokuWindow.cpp.i:
	$(MAKE) -f CMakeFiles/gomoku.dir/build.make CMakeFiles/gomoku.dir/src/GomokuWindow.cpp.i
.PHONY : src/GomokuWindow.cpp.i

src/GomokuWindow.s: src/GomokuWindow.cpp.s

.PHONY : src/GomokuWindow.s

# target to generate assembly for a file
src/GomokuWindow.cpp.s:
	$(MAKE) -f CMakeFiles/gomoku.dir/build.make CMakeFiles/gomoku.dir/src/GomokuWindow.cpp.s
.PHONY : src/GomokuWindow.cpp.s

src/MinMax.o: src/MinMax.cpp.o

.PHONY : src/MinMax.o

# target to build an object file
src/MinMax.cpp.o:
	$(MAKE) -f CMakeFiles/gomoku.dir/build.make CMakeFiles/gomoku.dir/src/MinMax.cpp.o
.PHONY : src/MinMax.cpp.o

src/MinMax.i: src/MinMax.cpp.i

.PHONY : src/MinMax.i

# target to preprocess a source file
src/MinMax.cpp.i:
	$(MAKE) -f CMakeFiles/gomoku.dir/build.make CMakeFiles/gomoku.dir/src/MinMax.cpp.i
.PHONY : src/MinMax.cpp.i

src/MinMax.s: src/MinMax.cpp.s

.PHONY : src/MinMax.s

# target to generate assembly for a file
src/MinMax.cpp.s:
	$(MAKE) -f CMakeFiles/gomoku.dir/build.make CMakeFiles/gomoku.dir/src/MinMax.cpp.s
.PHONY : src/MinMax.cpp.s

src/Pattern.o: src/Pattern.cpp.o

.PHONY : src/Pattern.o

# target to build an object file
src/Pattern.cpp.o:
	$(MAKE) -f CMakeFiles/gomoku.dir/build.make CMakeFiles/gomoku.dir/src/Pattern.cpp.o
.PHONY : src/Pattern.cpp.o

src/Pattern.i: src/Pattern.cpp.i

.PHONY : src/Pattern.i

# target to preprocess a source file
src/Pattern.cpp.i:
	$(MAKE) -f CMakeFiles/gomoku.dir/build.make CMakeFiles/gomoku.dir/src/Pattern.cpp.i
.PHONY : src/Pattern.cpp.i

src/Pattern.s: src/Pattern.cpp.s

.PHONY : src/Pattern.s

# target to generate assembly for a file
src/Pattern.cpp.s:
	$(MAKE) -f CMakeFiles/gomoku.dir/build.make CMakeFiles/gomoku.dir/src/Pattern.cpp.s
.PHONY : src/Pattern.cpp.s

src/Player.o: src/Player.cpp.o

.PHONY : src/Player.o

# target to build an object file
src/Player.cpp.o:
	$(MAKE) -f CMakeFiles/gomoku.dir/build.make CMakeFiles/gomoku.dir/src/Player.cpp.o
.PHONY : src/Player.cpp.o

src/Player.i: src/Player.cpp.i

.PHONY : src/Player.i

# target to preprocess a source file
src/Player.cpp.i:
	$(MAKE) -f CMakeFiles/gomoku.dir/build.make CMakeFiles/gomoku.dir/src/Player.cpp.i
.PHONY : src/Player.cpp.i

src/Player.s: src/Player.cpp.s

.PHONY : src/Player.s

# target to generate assembly for a file
src/Player.cpp.s:
	$(MAKE) -f CMakeFiles/gomoku.dir/build.make CMakeFiles/gomoku.dir/src/Player.cpp.s
.PHONY : src/Player.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/gomoku.dir/build.make CMakeFiles/gomoku.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/gomoku.dir/build.make CMakeFiles/gomoku.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/gomoku.dir/build.make CMakeFiles/gomoku.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/sfmlcanvas.o: src/sfmlcanvas.cpp.o

.PHONY : src/sfmlcanvas.o

# target to build an object file
src/sfmlcanvas.cpp.o:
	$(MAKE) -f CMakeFiles/gomoku.dir/build.make CMakeFiles/gomoku.dir/src/sfmlcanvas.cpp.o
.PHONY : src/sfmlcanvas.cpp.o

src/sfmlcanvas.i: src/sfmlcanvas.cpp.i

.PHONY : src/sfmlcanvas.i

# target to preprocess a source file
src/sfmlcanvas.cpp.i:
	$(MAKE) -f CMakeFiles/gomoku.dir/build.make CMakeFiles/gomoku.dir/src/sfmlcanvas.cpp.i
.PHONY : src/sfmlcanvas.cpp.i

src/sfmlcanvas.s: src/sfmlcanvas.cpp.s

.PHONY : src/sfmlcanvas.s

# target to generate assembly for a file
src/sfmlcanvas.cpp.s:
	$(MAKE) -f CMakeFiles/gomoku.dir/build.make CMakeFiles/gomoku.dir/src/sfmlcanvas.cpp.s
.PHONY : src/sfmlcanvas.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... gomoku"
	@echo "... moc_GomokuWindow.o"
	@echo "... moc_GomokuWindow.i"
	@echo "... moc_GomokuWindow.s"
	@echo "... src/ASFMLCanvas.o"
	@echo "... src/ASFMLCanvas.i"
	@echo "... src/ASFMLCanvas.s"
	@echo "... src/Game.o"
	@echo "... src/Game.i"
	@echo "... src/Game.s"
	@echo "... src/GomokuWindow.o"
	@echo "... src/GomokuWindow.i"
	@echo "... src/GomokuWindow.s"
	@echo "... src/MinMax.o"
	@echo "... src/MinMax.i"
	@echo "... src/MinMax.s"
	@echo "... src/Pattern.o"
	@echo "... src/Pattern.i"
	@echo "... src/Pattern.s"
	@echo "... src/Player.o"
	@echo "... src/Player.i"
	@echo "... src/Player.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/sfmlcanvas.o"
	@echo "... src/sfmlcanvas.i"
	@echo "... src/sfmlcanvas.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

